### PR TITLE
Update

### PR DESCRIPTION
**Pull request by bbhtt**

### CODE REVIEW

**Comment by gasinvein** [comment]
Did you test this, does it work as expected?

**Comment by bbhtt** [comment]
> Did you test this, does it work as expected?

Yes seems to work. Except grabbing media keys probably never worked:

```
** (com.github.artemanufrij.playmyvideos:2): WARNING **: 06:24:06.216: MediaKeys.vala:56: Could not grab media player keys: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
```

I think this https://github.com/artemanufrij/playmyvideos/blob/5aef166b21856d7847e740ff98b4bbfb0e20a51f/src/Interfaces/MediaKeys.vala#L45 should be:

```patch
- media_keys = Bus.get_proxy_sync (BusType.SESSION, "org.gnome.SettingsDaemon", "/org/gnome/SettingsDaemon/MediaKeys");
+ media_keys = Bus.get_proxy_sync (BusType.SESSION, "org.gnome.SettingsDaemon.MediaKeys", "/org/gnome/SettingsDaemon/MediaKeys");
```

**Comment by gasinvein** [comment]
Thanks.

**Comment by bbhtt** [comment]
Do you want a patch for the above issue? I've opened https://github.com/artemanufrij/playmyvideos/issues/49

**Comment by gasinvein** [comment]
The app seems abandoned, no code updates since 2019.

**Pull request merged**
